apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-team-quota
  namespace: dev-team
spec:
  hard:
    pods: "5"
    requests.cpu: "1"  #minimun
    requests.memory: 2Gi
    limits.cpu: "2"    #maximum
    limits.memory: 3Gi