apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileshare-pvc
spec:
  storageClassName: custom-fileshare-storageclass
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi