apiVersion: apps/v1
kind: Deployment
metadata:
  name:  cpu-hpa-demo
  labels:
    app:  cpu-hpa-demo
spec:
  selector:
    matchLabels:
      app: cpu-hpa-demo
  replicas: 1
  template:
    metadata:
      labels:
        app:  cpu-hpa-demo
    spec:
      containers:
      - name:  cpu-hpa-demo
        image:  nginx
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: cpu-hpa-demo
spec:
  selector:
    app: cpu-hpa-demo
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP