apiVersion: v1
kind: Pod
metadata:
  name: multi-c-pod
  namespace: default
  labels:
    app: multi-c-pod
spec:
  containers:
  - name: nginx
    image: nginx

  - name: sidecar
    image: python:3
    command: ["python"]
    args:
      - "-c"
      - "import math; num = 5; result = math.factorial(num); print(f'The factorial of {num} is {result}')"
