#kind: # https://kubernetes.io/docs/reference/access-authn-authz/rbac/
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-log-reader-ClusterRoleBinding
subjects:
- kind: User
  name: ***********
  apiGroup: rbac.authorization.k8s.io
- kind: group
  name: ***********
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-log-reader-clusterrole
  apiGroup: rbac.authorization.k8s.io

